#ddev-generated
# If you remove the ddev-generated line above you
# are responsible for maintaining this file. DDEV will not then
# update it, for example if you add `additional_hostnames`, etc.

http:
  routers:
    lara-collab-xhgui-80-http:
      entrypoints:
        - http-8143
      rule: HostRegexp(`^lara-collab\.ddev\.site$`)
      
      service: "lara-collab-xhgui-80"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "lara-collab-redirectHttps"
    lara-collab-web-80-http:
      entrypoints:
        - http-80
      rule: HostRegexp(`^lara-collab\.ddev\.site$`)
      
      service: "lara-collab-web-80"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "lara-collab-redirectHttps"
    lara-collab-web-8025-http:
      entrypoints:
        - http-8025
      rule: HostRegexp(`^lara-collab\.ddev\.site$`)
      
      service: "lara-collab-web-8025"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "lara-collab-redirectHttps"
    
    
    lara-collab-xhgui-80-https:
      entrypoints:
        - http-8142
      rule: HostRegexp(`^lara-collab\.ddev\.site$`)
      
      service: "lara-collab-xhgui-80"
      ruleSyntax: v3
      
      tls: true
      
    
    
    lara-collab-web-80-https:
      entrypoints:
        - http-443
      rule: HostRegexp(`^lara-collab\.ddev\.site$`)
      
      service: "lara-collab-web-80"
      ruleSyntax: v3
      
      tls: true
      
    lara-collab-web-8025-https:
      entrypoints:
        - http-8026
      rule: HostRegexp(`^lara-collab\.ddev\.site$`)
      
      service: "lara-collab-web-8025"
      ruleSyntax: v3
      
      tls: true
      
    

  middlewares:
    lara-collab-redirectHttps:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    lara-collab-xhgui-80:
      loadbalancer:
        servers:
          - url: http://ddev-lara-collab-xhgui:80
        
    
    lara-collab-web-80:
      loadbalancer:
        servers:
          - url: http://ddev-lara-collab-web:80
        
    lara-collab-web-8025:
      loadbalancer:
        servers:
          - url: http://ddev-lara-collab-web:8025
        
    
    
    

tls:
  certificates:
    - certFile: /mnt/ddev-global-cache/traefik/certs/lara-collab.crt
      keyFile: /mnt/ddev-global-cache/traefik/certs/lara-collab.key